// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4rJU6fW9b44DojVPBwWUtX19CtSZPALc',
    appId: '1:407414862469:web:d9b0ecd02decd2a0bb2fec',
    messagingSenderId: '407414862469',
    projectId: 'erp-school-8d980',
    authDomain: 'erp-school-8d980.firebaseapp.com',
    storageBucket: 'erp-school-8d980.appspot.com',
    measurementId: 'G-10W806TPM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWS4bgs-uDXDyXf5D32YBYb8uWfWxrI1M',
    appId: '1:407414862469:android:99578d7fbaec0d33bb2fec',
    messagingSenderId: '407414862469',
    projectId: 'erp-school-8d980',
    storageBucket: 'erp-school-8d980.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN3o6BGRpVX37moCGig8UYv1f4RzFvwk0',
    appId: '1:407414862469:ios:f4e23d104bc56069bb2fec',
    messagingSenderId: '407414862469',
    projectId: 'erp-school-8d980',
    storageBucket: 'erp-school-8d980.appspot.com',
    iosBundleId: 'com.example.erpSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN3o6BGRpVX37moCGig8UYv1f4RzFvwk0',
    appId: '1:407414862469:ios:9bea80b9664e36a8bb2fec',
    messagingSenderId: '407414862469',
    projectId: 'erp-school-8d980',
    storageBucket: 'erp-school-8d980.appspot.com',
    iosBundleId: 'com.example.erpSchool.RunnerTests',
  );
}
